default: &default
  adapter: postgresql
  encoding: utf8
  username: dockerplay
  password: password1
  host: localhost
  port: 5442
  pool: 5

development:
  <<: *default
  database: dockerplay

test:
  <<: *default
  database: dockerplay_test
